---
version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/New York
      - SUBDOMAINS=
      - TOKEN=
      - LOG_FILE=false #optional
    restart: unless-stopped
